---
# yamllint disable rule:line-length
name: CD

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      MANIFESTS_PATH:
        required: true
        type: string
        default: .k8s
      APP_NAME:
        required: false
        type: string
env:
  APP_NAME: ${{ github.repository }}

jobs:
  sync-stg:
    runs-on: self-hosted
    environment: staging
    steps:
      - name: Login to ArgoCD
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: login "${{ secrets.ARGOCD_URL }}"
          options: --grpc-web --username "${{ secrets.ARGOCD_USER }}" --password "${{ secrets.ARGOCD_PASS }}"

      - name: Get Short SHA
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        id: sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: ArgoCD Overwrite Image Tag
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app set ${{ env.APP_NAME }}-stg
          options: --kustomize-image "ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}"

      - name: Sync Staging
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app sync ${{ env.APP_NAME }}-stg

  sync-prd:
    runs-on: self-hosted
    needs: sync-stg
    environment: production
    steps:
      - name: Login to ArgoCD
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: login "${{ secrets.ARGOCD_URL }}"
          options: --grpc-web --username "${{ secrets.ARGOCD_USER }}" --password "${{ secrets.ARGOCD_PASS }}"

      - name: Get Short SHA
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        id: sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: ArgoCD Overwrite Image Tag
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app set ${{ env.APP_NAME }}-prd
          options: --kustomize-image "ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}"

      - name: Sync Production
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app sync ${{ env.APP_NAME }}-prd
