---
# yamllint disable rule:line-length
name: CD

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      APP_NAME:
        required: false
        type: string
      ENABLE_STG:
        required: false
        type: string
        default: 'true'
      ENABLE_PRD:
        required: false
        type: string
        default: 'true'
    secrets:
      ALERTS_CHANNEL:
        required: true
      ARGOCD_URL:
        required: true
      ARGOCD_USER:
        required: true
      ARGOCD_PASS:
        required: true


env:
  ALERTS_CHANNEL: "${{ secrets.SAE_ALERTS_CHANNEL }}"
  ARGOCD_URL: "${{ secrets.ARGOCD_URL }}"
  ARGOCD_USER: "${{ secrets.ARGOCD_USER }}"
  ARGOCD_PASS: "${{ secrets.ARGOCD_PASS }}"

jobs:
  sync-stg:
    if: ${{ inputs.ENABLE_STG == 'true' }}
    runs-on: self-hosted
    environment: staging
    steps:
      - name: Get app name
        run: echo "APP_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Login to ArgoCD
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: login "${{ secrets.ARGOCD_URL }}"
          options: --grpc-web --username "${{ secrets.ARGOCD_USER }}" --password "${{ secrets.ARGOCD_PASS }}"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Add project to ArgoCD
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: proj create
          options: -f .argocd/project-stg.yaml --upsert

      - name: Add application to ArgoCD
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app create
          options: -f .argocd/app-stg.yaml --upsert

      - if: ${{ github.event.workflow_run.conclusion == 'success'}}
        name: Get Short SHA
        id: sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: ArgoCD Overwrite Image Tag
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app set --revision ${{ steps.sha.outputs.sha8 }} "${{ env.APP_NAME }}-stg"
          options: --kustomize-image "ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}"

      - name: Sync Staging
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app sync "${{ env.APP_NAME }}-stg"

  sync-prd:
    if: ${{ !failure() && inputs.ENABLE_PRD == 'true' }}
    needs: sync-stg
    runs-on: self-hosted
    environment: production
    steps:
      - name: Get app name
        run: echo "APP_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Login to ArgoCD
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: login "${{ secrets.ARGOCD_URL }}"
          options: --grpc-web --username "${{ secrets.ARGOCD_USER }}" --password "${{ secrets.ARGOCD_PASS }}
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add project to ArgoCD
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: proj create
          options: -f .argocd/project-prd.yaml --upsert

      - name: Add application to ArgoCD
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app create
          options: -f .argocd/app-prd.yaml --upsert

      - name: Get Short SHA
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        id: sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: ArgoCD Overwrite Image Tag
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app set ${{ steps.sha.outputs.sha8 }} "${{ env.APP_NAME }}-prd"
          options: --kustomize-image "ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}"

      - name: Sync Production
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app sync "${{ env.APP_NAME }}-prd"

      - name: Deploy ${{ env.APP_NAME }} prd version ${{ steps.sha.outputs.sha8 }} by user ${{ github.actor }}
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "${{ env.ALERTS_CHANNEL }}"