---
name: docker-build
on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
        default: ghcr.io
      USERNAME:
        required: true
        type: string
      PASSWORD:
        required: true
        type: string
env:
  REGISTRY: ${{ inputs.REGISTRY }}
  USERNAME: ${{ secrets.GH_REGISTRY_USERNAME }}
  PASSWORD: ${{ secrets.GH_REGISTRY_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    needs: kubeval
    steps:
      - name: Get Short SHA
        id: sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}
            ghcr.io/${{ github.repository }}:latest
